### ISSUE TITLE
Create Python port for `doilit` as `doi2ietf`

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/doi2ietf-py#1]
`doilit` is available in Ruby from https://github.com/cabo/kramdown-rfc2629/blob/master/bin/doilit

This task is to create a port of that in Python and add tests.

The tool takes an input of a DOI identifier, and retrieves the DOI metadata in citeproc format for it.

For example:

https://dx.doi.org/10.6028/NIST.SP.800-183

```sh
curl -H "Accept: application/citeproc+json" https://dx.doi.org/10.6028/NIST.SP.800-183
```

=>

```
<html><head><title>Handle Redirect</title></head>
<body><a href="https://data.crossref.org/10.6028%2FNIST.SP.800-183">https://data.crossref.org/10.6028%2FNIST.SP.800-183</a></body></html>
```

Then:

```sh
curl -H "Accept: application/citeproc+json" https://data.crossref.org/10.6028%2FNIST.SP.800-183
```

=> 
```json
{
  "institution": {
    "name": "National Institute of Standards and Technology",
    "place": [
      "Gaithersburg, MD"
    ],
    "acronym": [
      "NIST"
    ]
  },
  "indexed": {
    "date-parts": [
      [
        2021,
        5,
        11
      ]
    ],
    "date-time": "2021-05-11T17:04:57Z",
    "timestamp": 1620752697313
  },
  "publisher-location": "Gaithersburg, MD",
  "reference-count": 0,
  "publisher": "National Institute of Standards and Technology",
  "content-domain": {
    "domain": [

    ],
    "crossmark-restriction": false
  },
  "DOI": "10.6028/nist.sp.800-183",
  "type": "report",
  "created": {
    "date-parts": [
      [
        2016,
        7,
        19
      ]
    ],
    "date-time": "2016-07-19T21:41:31Z",
    "timestamp": 1468964491000
  },
  "source": "Crossref",
  "is-referenced-by-count": 33,
  "title": "Networks of 'things'",
  "prefix": "10.6028",
  "author": [
    {
      "given": "Jeffrey M",
      "family": "Voas",
      "sequence": "first",
      "affiliation": [

      ]
    }
  ],
  "member": "4068",
  "published-online": {
    "date-parts": [
      [
        2016
      ]
    ]
  },
  "container-title": [

  ],
  "original-title": [

  ],
  "deposited": {
    "date-parts": [
      [
        2018,
        3,
        6
      ]
    ],
    "date-time": "2018-03-06T09:44:48Z",
    "timestamp": 1520329488000
  },
  "score": 1.0,
  "subtitle": [
    ""
  ],
  "short-title": [

  ],
  "issued": {
    "date-parts": [
      [
        2016
      ]
    ]
  },
  "references-count": 0,
  "URL": "http://dx.doi.org/10.6028/NIST.SP.800-183",
  "relation": {
  }
}
```

Then convert it into BibXML format.

**Comment by ronaldtse** [comment]
Maybe we rename this to doi2ietf...

**Comment by yablokov** [comment]
Hi!

Initial release ready, please check it.

**Comment by ronaldtse** [comment]
Thanks @yablokov ! I will post additional issues including GHA testing and pip packaging.

**Comment by strogonoff** [comment]
@ronaldtse

Per my 1:1 conversation with @yablokov:

* Vladimir will add the appropriate `setup.py` to allow installing this package using PIP shortly.

  * Which license should be used?
  * If we want to release this package on PyPI, is there a Ribose or IETF-Ribose org there, or should personal account be used for this? (Note that we don’t have to publish on PyPI, since PIP can use a Git repository as source as long as there’s a valid `setup.py`.)

* Currently, tests in this implementation invoke Ruby gem and use the results it produces as a reference to compare with.

  * At a future stage, it’ll be wrapped into more conventional test runner and any dependency on Ruby library in tests will likely be removed, but I encouraged Vladimir to release as is since currently the tests achieve the purpose at validating the implementation.

* Vladimir noted that there appear to be issues with the Ruby implementation we take as a reference. For example, dates omit day for some reason

      "10.1002/9780470974582.ch12"
      XML element (from doilit): b'<date year="2010" month="October"/>\n'
      InsertAttrib(node='/root/reference[7]/front/date[1]', name='day', value='04')

**Comment by ronaldtse** [comment]
> * Which license should be used?

I've added the MIT license.

> * If we want to release this package on PyPI, is there a Ribose or IETF-Ribose org there, or should personal account be used for this? (Note that we don’t have to publish on PyPI, since PIP can use a Git repository as source as long as there’s a valid `setup.py`.)

Yes it's now released under the Ribose account at PyPi.
